//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DykResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DykResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.DykResources", typeof(DykResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noinclude&gt;{{Знаете ли вы архив|2024}}&lt;/noinclude&gt;
        ///
        ///== 15—18 мая ==
        ///
        ///[[Файл:Undressed funernal effigy of Catherine de Valois, Queen of England.jpg|right|140px|Деревянная скульптура королевы Англии Екатерины Валуа]]
        ///* Сцена разговора &apos;&apos;&apos;[[Екатерина Валуа|будущей английской королевы]]&apos;&apos;&apos; {{наилл}} с подругой в пьесе «[[Генрих V (пьеса)|Генрих V]]» считается одной из самых [[Обсценная лексика|скабрёзных]] у Шекспира.
        ///* В международной политике Таиланд пытается усидеть на &apos;&apos;&apos;[[Американо-таиландские отношения|дв [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArchiveAfter {
            get {
                return ResourceManager.GetString("ArchiveAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noinclude&gt;{{Знаете ли вы архив|2024}}&lt;/noinclude&gt;
        ///
        ///== 9—12 мая ==
        ///
        ///[[Файл:Baggins residence &apos;Bag End&apos; with party sign.jpg|right|140px|Бэг Энд]]
        ///* Английский журналист считает, что [[Прототип персонажа|прототипом]] Лобелии Саквилль-Бэггинс, желавшей заполучить &apos;&apos;&apos;[[Бэг Энд|жилище Бильбо]]&apos;&apos;&apos; {{наилл}} во «[[Властелин колец|Властелине колец]]», была [[Сэквилл-Уэст, Вита|писательница со схожей фамилией]].
        ///* &apos;&apos;&apos;[[Аграрии (партия)|Германская аграрная партия]]&apos;&apos;&apos; начала с [[Фритредерство|фритредерства]], а закон [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArchiveBefore {
            get {
                return ResourceManager.GetString("ArchiveBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{shortcut|ПРО:ЗЛВ-Ч|ПРО:ЗЛВЧ}}
        ///{{#switch:{{SUBPAGENAME}}|Предпросмотр черновиков=|&lt;noinclude&gt;{{toc-left}}{{ЗЛВ-Навигация}}{{-}}&lt;/noinclude&gt; }}
        ///
        ///== Выпуск 15 мая (выпускающий Горизонт событий) ==
        ///[[Файл:Николай Михайлович Покровский.png|right|130px|Николай Михайлович Покровский]]
        ///* &apos;&apos;&apos;[[Покровский, Николай Михайлович (врач)|Дядя Булгакова]]&apos;&apos;&apos; {{наилл}} так и не узнал, что является прототипом [[Филипп Филиппович Преображенский|профессора Преображенского]].
        ///* &apos;&apos;&apos;«[[Горбунов, Александр Павлович|Сверхректор св [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DraftAfter {
            get {
                return ResourceManager.GetString("DraftAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///== Выпуск 6 мая (выпускающий Fordaemdur) ==
        ///* &apos;&apos;&apos;[[Сминате, Надя|Надя Сминате]]&apos;&apos;&apos; {{наилл}} стала первым мэром [[Марокко|марокканского]] происхождения во [[Лондерзел|Фландрии]].
        ///** Традиционно имена используют для анонсов людей, которые всем известны, например, Эйнштейн. А кто такая &quot;Надя Сминате&quot;? Нужно заменить на любое определение. Этническая марокканка. Филолог. [[Лиценциат]]ка.— [[У:Hammunculs|Hammunculs]] ([[ОУ:Hammunculs|обс.]]) 08:38, 5 апреля 2024 (UTC)
        ///**:Благодарю, исправил! — &apos;&apos;[[Участник:For [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DraftArchiveAfter {
            get {
                return ResourceManager.GetString("DraftArchiveAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///== Выпуск 6 мая (выпускающий Fordaemdur) ==
        ///* &apos;&apos;&apos;[[Сминате, Надя|Надя Сминате]]&apos;&apos;&apos; {{наилл}} стала первым мэром [[Марокко|марокканского]] происхождения во [[Лондерзел|Фландрии]].
        ///** Традиционно имена используют для анонсов людей, которые всем известны, например, Эйнштейн. А кто такая &quot;Надя Сминате&quot;? Нужно заменить на любое определение. Этническая марокканка. Филолог. [[Лиценциат]]ка.— [[У:Hammunculs|Hammunculs]] ([[ОУ:Hammunculs|обс.]]) 08:38, 5 апреля 2024 (UTC)
        ///**:Благодарю, исправил! — &apos;&apos;[[Участник:For [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DraftArchiveBefore {
            get {
                return ResourceManager.GetString("DraftArchiveBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{shortcut|ПРО:ЗЛВ-Ч|ПРО:ЗЛВЧ}}
        ///{{#switch:{{SUBPAGENAME}}|Предпросмотр черновиков=|&lt;noinclude&gt;{{toc-left}}{{ЗЛВ-Навигация}}{{-}}&lt;/noinclude&gt; }}
        ///
        ///== Выпуск 15 мая (выпускающий Горизонт событий) ==
        ///[[Файл:Николай Михайлович Покровский.png|right|130px|Николай Михайлович Покровский]]
        ///* &apos;&apos;&apos;[[Покровский, Николай Михайлович (врач)|Дядя Булгакова]]&apos;&apos;&apos; {{наилл}} так и не узнал, что является прототипом [[Филипп Филиппович Преображенский|профессора Преображенского]].
        ///* &apos;&apos;&apos;«[[Горбунов, Александр Павлович|Сверхректор св [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DraftBefore {
            get {
                return ResourceManager.GetString("DraftBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ЗЛВ-Навигация}}
        ///{{Архив|2012|2013|2014|2015|2016|2017|2018|2019|2020|2021|2022|2023|2024}}
        ///{{/NB}}
        ///__TOC__
        ///
        ///== Выпуск 12 мая (в складчину) ==
        ///* &quot;считал уездный городок с за́мком&quot; - что-то явно пропущено. [[У:Vcohen|Vcohen]] ([[ОУ:Vcohen|обс.]]) 15:17, 17 апреля 2024 (UTC)
        ///* &quot;селф-мейд женщина&quot; - в русском языке нет прилагательного &quot;селф-мейд&quot;, надо это писать через два дефиса (&quot;селф-мейд-женщина&quot;), но тогда получается полная ерунда. [[У:Vcohen|Vcohen]] ([[ОУ:Vcohen|обс.]]) 15:17, 17 апреля 2024 (UTC)
        ///*: В [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DraftTalkAfter {
            get {
                return ResourceManager.GetString("DraftTalkAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ЗЛВ-Навигация}}
        ///{{Архив|2012|2013|2014|2015|2016|2017|2018|2019|2020|2021|2022|2023|2024}}
        ///{{/NB}}
        ///__TOC__
        ///
        ///== Выпуск 12 мая (в складчину) ==
        ///* &quot;считал уездный городок с за́мком&quot; - что-то явно пропущено. [[У:Vcohen|Vcohen]] ([[ОУ:Vcohen|обс.]]) 15:17, 17 апреля 2024 (UTC)
        ///* &quot;селф-мейд женщина&quot; - в русском языке нет прилагательного &quot;селф-мейд&quot;, надо это писать через два дефиса (&quot;селф-мейд-женщина&quot;), но тогда получается полная ерунда. [[У:Vcohen|Vcohen]] ([[ОУ:Vcohen|обс.]]) 15:17, 17 апреля 2024 (UTC)
        ///*: В [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DraftTalkBefore {
            get {
                return ResourceManager.GetString("DraftTalkBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екатерина Валуа
        ///Сцена разговора &apos;&apos;&apos;[[Екатерина Валуа|будущей английской королевы]]&apos;&apos;&apos; {{наилл}} с подругой в пьесе «[[Генрих V (пьеса)|Генрих V]]» считается одной из самых [[Обсценная лексика|скабрёзных]] у Шекспира.!!![[Файл:Undressed funernal effigy of Catherine de Valois, Queen of England.jpg|right|140px|Деревянная скульптура королевы Англии Екатерины Валуа]]
        ///!!!
        ///Американо-таиландские отношения
        ///В международной политике Таиланд пытается усидеть на &apos;&apos;&apos;[[Американо-таиландские отношения|двух]]&apos;&apos;&apos; разных &apos;&apos;&apos;[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hooks {
            get {
                return ResourceManager.GetString("Hooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{/Шапка}}
        ///&lt;!-- Не удаляйте шапку! Она необходима для корректной работы страницы --&gt;
        ///
        ///=== {{злв-статус|до=2024-07-03T10:59:14}} [[Сборная Англии по пляжному футболу]] ===
        ///* Средний возраст &apos;&apos;&apos;[[Сборная Англии по пляжному футболу|сборной Англии]]&apos;&apos;&apos; на первом в истории [[Чемпионат мира по пляжному футболу 1995|чемпионате мира по пляжному футболу]] составлял 38 лет. [[У:Mitte27|Mitte27]] ([[ОУ:Mitte27|обс.]]) 12:34, 3 апреля 2024 (UTC)
        ///** &apos;&apos;Ну или если перефразировать и обыграть...&apos;&apos; На первый [[чемпионат мир [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PreparationAfter {
            get {
                return ResourceManager.GetString("PreparationAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{/Шапка}}
        ///&lt;!-- Не удаляйте шапку! Она необходима для корректной работы страницы --&gt;
        ///
        ///=== {{злв-статус|до=2024-07-03T10:59:14}} [[Сборная Англии по пляжному футболу]] ===
        ///* Средний возраст &apos;&apos;&apos;[[Сборная Англии по пляжному футболу|сборной Англии]]&apos;&apos;&apos; на первом в истории [[Чемпионат мира по пляжному футболу 1995|чемпионате мира по пляжному футболу]] составлял 38 лет. [[У:Mitte27|Mitte27]] ([[ОУ:Mitte27|обс.]]) 12:34, 3 апреля 2024 (UTC)
        ///** &apos;&apos;Ну или если перефразировать и обыграть...&apos;&apos; На первый [[чемпионат мир [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PreparationBefore {
            get {
                return ResourceManager.GetString("PreparationBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noinclude&gt;{{doc}}&lt;/noinclude&gt;
        ///&lt;!-- BOT — между этими комментариями бот Lê Lợi (bot) вставит из черновика очередной выпуск --&gt;
        ///[[Файл:Milky Way, Palau.jpg|right|120px|Гавань на палауском острове Корор]]
        ///* На [[Палау]] {{наилл}} формируется &apos;&apos;&apos;[[Палауский диалект английского языка|собственный диалект английского]]&apos;&apos;&apos;.
        ///* &apos;&apos;&apos;[[Хиллз, Арнолд|Соратник]]&apos;&apos;&apos; [[Махатма Ганди|Махатмы Ганди]] по [[Вегетарианское общество|вегетарианскому кружку]] руководил строительством военного корабля.
        ///* В 2020-е стало модно вспоми [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateAfter {
            get {
                return ResourceManager.GetString("TemplateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noinclude&gt;{{doc}}&lt;/noinclude&gt;
        ///&lt;!-- BOT — между этими комментариями бот Lê Lợi (bot) вставит из черновика очередной выпуск --&gt;
        ///[[Файл:Undressed funernal effigy of Catherine de Valois, Queen of England.jpg|right|140px|Деревянная скульптура королевы Англии Екатерины Валуа]]
        ///* Сцена разговора &apos;&apos;&apos;[[Екатерина Валуа|будущей английской королевы]]&apos;&apos;&apos; {{наилл}} с подругой в пьесе «[[Генрих V (пьеса)|Генрих V]]» считается одной из самых [[Обсценная лексика|скабрёзных]] у Шекспира.
        ///* В международной политике Таиланд п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateBefore {
            get {
                return ResourceManager.GetString("TemplateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noinclude&gt;{{ЗЛВ-Навигация}}&lt;/noinclude&gt;
        ///
        ///== Расписание обновлений ==
        ///{| class=&quot;wikitable mw-notalk&quot;
        ///|-
        ///! scope=&quot;col&quot; | Выпуск
        ///! scope=&quot;col&quot; | Выпускающий
        ///|-
        ///| {{Злвч|Горизонт событий|15 мая|+}} || [[Участник:Горизонт событий|ʜᴏʀɪᴢᴏɴ]] [[Обсуждение участника:Горизонт событий|[ᴅɪsᴄᴜʀsᴜs]]] [[Служебная:Вклад/Горизонт событий|[ᴄᴏɴᴛʀɪʙs]]] 07:51, 21 апреля 2024 (UTC)
        ///|-
        ///| {{злвч|Sigwald|21 мая|+}} || [[У:Sigwald|Sigwald]] ([[ОУ:Sigwald|обс.]]) 13:00, 9 апреля 2024 (UTC)
        ///|-
        ///| {{злвч|Oleg4280|24 мая|+}} || [[У:Ol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimetableAfter {
            get {
                return ResourceManager.GetString("TimetableAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noinclude&gt;{{ЗЛВ-Навигация}}&lt;/noinclude&gt;
        ///
        ///== Расписание обновлений ==
        ///{| class=&quot;wikitable mw-notalk&quot;
        ///|-
        ///! scope=&quot;col&quot; | Выпуск
        ///! scope=&quot;col&quot; | Выпускающий
        ///|-
        ///| {{Злвч|Горизонт событий|15 мая|+}} || [[Участник:Горизонт событий|ʜᴏʀɪᴢᴏɴ]] [[Обсуждение участника:Горизонт событий|[ᴅɪsᴄᴜʀsᴜs]]] [[Служебная:Вклад/Горизонт событий|[ᴄᴏɴᴛʀɪʙs]]] 07:51, 21 апреля 2024 (UTC)
        ///|-
        ///| {{злвч|Fordaemdur|18 мая|+}} || — &apos;&apos;[[Участник:Fordaemdur|Φορδαεμδύρ]] [[Обсуждение участника:Fordaemdur|✉️]]&apos;&apos; 00:55, 4 апреля 2024 (UTC)
        ///|- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimetableBefore {
            get {
                return ResourceManager.GetString("TimetableBefore", resourceCulture);
            }
        }
    }
}
